[package]
name = "csv-money"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
rust_decimal = { version = "1.39.0", features = ["macros"] }
serde = { version = "1.0.228", features = ["std", "derive"] }
thiserror = "2.0.17"

[dev-dependencies]
tempfile = "3.23.0"
